export const metadata = {
  title: 'Terms of Service | Manabu',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-[#121317] text-[#1a1a2e] dark:text-[#e8e8f0]">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <a href="/" className="text-sm font-bold text-blue-500 hover:underline mb-8 inline-block">&larr; Back to Manabu</a>

        <h1 className="text-4xl font-black mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-12">Last updated: March 2026</p>

        <div className="space-y-10 text-[15px] leading-relaxed">

          <section>
            <h2 className="text-xl font-bold mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using Manabu (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">2. Description of Service</h2>
            <p>Manabu is an AI-powered learning platform that generates interactive courses and quizzes on any topic. The Service is provided for personal, non-commercial educational use.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">3. User Accounts</h2>
            <p>You may create an account using email/password or a third-party OAuth provider (Google, X/Twitter). You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">4. User Content and Conduct</h2>
            <p>You agree not to use the Service to generate, store, or share content that is illegal, harmful, abusive, or violates the rights of others. We reserve the right to suspend accounts that violate these terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">5. AI-Generated Content</h2>
            <p>Course content is generated by third-party AI models (including Groq-hosted models). We do not guarantee the accuracy, completeness, or reliability of AI-generated content. You should verify important information from authoritative sources.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">6. Intellectual Property</h2>
            <p>The Manabu platform, its design, and underlying code are owned by the developers. AI-generated course content produced through your use of the Service is yours to use for personal learning purposes.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">7. Disclaimer of Warranties</h2>
            <p>The Service is provided &quot;as is&quot; without warranties of any kind. We do not warrant that the Service will be uninterrupted, error-free, or that AI-generated content will be accurate.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">8. Limitation of Liability</h2>
            <p>To the fullest extent permitted by law, Manabu and its developers shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">9. Changes to Terms</h2>
            <p>We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the updated Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">10. Contact</h2>
            <p>For questions about these Terms, please contact us through the app.</p>
          </section>

        </div>
      </div>
    </div>
  );
}
